openapi: 3.0.0
info:
  title: Mi API Aventura
  description: Documentación interactiva para la API Express
  version: 1.0.0

servers:
  - url: https://mod-7-render.onrender.com/

paths:
  /:
    get:
      summary: Verifica que el servidor está funcionando
      responses:
        '200':
          description: Respuesta exitosa

  /api/v1/login:
    post:
      summary: Login de usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                correo:
                  type: string
                  example: ana.martinez@example.com
      responses:
        '200':
          description: Login exitoso
        '400':
          description: Correo no encontrado
        '404':
          description: Usuario no encontrado
        '500':
          description: Error interno del servidor

  /api/v1/usuarios:
    get:
      summary: Obtener todos los usuarios (requiere token)
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Lista de usuarios
        '401':
          description: Token no proporcionado o inválido
        '500':
          description: Error al obtener usuarios

  /api/v1/saludo:
    get:
      summary: Saludo personalizado
      parameters:
        - name: nombre
          in: query
          required: false
          schema:
            type: string
            example: Leroy
      responses:
        '200':
          description: Saludo exitoso
        '400':
          description: Nombre no proporcionado

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
